#!/bin/bash
# 0-world_wide_web

DOMAIN=$1
SUBDOMAIN=$2

get_dns_info() {
  local SUB=$1
  local DOMAIN=$2
  local IP=$(dig +short "$SUB.$DOMAIN")
  echo "The subdomain $SUB is a A record and points to $IP"
}


if [ -n "$SUBDOMAIN" ]; then
  get_dns_info "$SUBDOMAIN.$DOMAIN"
else
  for name in www lb-01 web-01 web-02; do
    get_dns_info "$name.$DOMAIN"
  done
fi
