#!/usr/bin/env bash

DOMAIN=$1
SUBDOMAIN=$2

get_record() {
    local sub="$1"
    local domain="$2"
    local full="${sub}.${domain}"

    local result
    result=$(dig "$full" | awk '/^;; ANSWER SECTION:/ {getline; print $4, $5}')

    local type
    type=$(echo "$result" | awk '{print $1}')

    local ip
    ip=$(echo "$result" | awk '{print $2}')

    echo "The subdomain $sub is a $type record and points to $ip"
}

if [ -z "$SUBDOMAIN" ]; then
    for sub in www lb-01 web-01 web-02; do
        get_record "$sub" "$DOMAIN"
    done
else
    get_record "$SUBDOMAIN" "$DOMAIN"
fi
