#!/bin/bash
python3 -c 'import os;n=int("".join(str("ewatr".index(c))for c in os.environ["WATER"]),5)+int("".join(str("stir.".index(c))for c in os.environ["STIR"]),5);e="bestchol";r="";exec("while n:\n r=e[n%8]+r\n n//=8");print(r)'
