#!/bin/bash
python3 -c 'e="bestchol";w=int("".join([str("ewatr".index(c))for c in __import__("os").environ["WATER"]]),5);s=int("".join([str("stir.".index(c))for c in __import__("os").environ["STIR"]]),5);n=w+s;r="";exec("while n:r=e[n%8]+r;n//=8");print(r)'
