#!/bin/bash
python3 -c 'a="bestchol";w=int("".join([str("water".index(c)) for c in __import__("os").environ["WATER"]]),5);s=int("".join([str("stir.".index(c)) for c in __import__("os").environ["STIR"]]),5);n=w+s;r="";exec("while n:r=a[n%8]+r;n//=8");print(r)'
