#!/usr/bin/env bash
# this script that transfers a file from our client to a server.
if [ $# -l 3 ]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi
echo "sftp ubuntu@54.237.107.153" || 
