#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me { return 301 https:\/\/www.walaeddine.com;}' /etc/nginx/sites-available/default
sudo service nginx start
