#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.
#sudo apt-get update
#sudo apt-get install -y nginx
#sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
sudo sed '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/ permanent;' /etc/nginx/sites-available/default
sudo service nginx reload
