#!/usr/bin/env bash
#shellcheck disable=SC2154
sudo apt-get update
sudo apt-get install -y nginx
sudo sh -c 'echo "Wach A Wala" > /var/www/html/index.nginx-debian.html'
sudo sh -c "echo \"Ceci n'est pas une page\" > /var/www/html/404.html"
sudo sed -i '/^http {/a \    error_page 404 404.html;' /etc/nginx/nginx.conf
sudo sed -i '/^http {/a\    addd_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo service nginx restart
