#!/bin/bash

apt-get update -y
apt-get install nginx -y

HOSTNAME=$(hostname)

# Add custom header to nginx config
sed -i "/^\\s*server_name _;/a \\tadd_header X-Served-By \$hostname;" /etc/nginx/sites-available/default

service nginx restart || nginx -s reload
