#!/bin/bash

apt-get update -y
apt-get install haproxy -y

cat << CONFIG > /etc/haproxy/haproxy.cfg
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server web1 [WEB_01_PRIVATE_IP]:80 check
    server web2 [WEB_02_PRIVATE_IP]:80 check
CONFIG

# Replace with your actual web server private IPs
sed -i 's/\[WEB_01_PRIVATE_IP\]/10.0.0.1/' /etc/haproxy/haproxy.cfg
sed -i 's/\[WEB_02_PRIVATE_IP\]/10.0.0.2/' /etc/haproxy/haproxy.cfg

service haproxy restart
