#!/usr/bin/env bash
#shellcheck disable=SC2154
sudo apt-get update
sudo apt-get install -y haproxy
sudo tee -a /etc/haproxy/haproxy.cfg <<EOF
frontend web
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    server 446193-web-01 54.237.91.183:80 check
    server 446193-web-02 54.173.37.227:80 check
EOF
sudo sed -i "9i ENABLED=1" /etc/default/haproxy
sudo service haproxy restart
