#!/usr/bin/env bash
# this script changes the localhost ip and facebook ip
cp /etc/hosts ~/hosts.new
hos="8.8.8.8   facebook.com"
echo "$hos" >> ~/hosts.new

sudo sed -i 's/127.0.0.1[[:space:]]\+localhost/127.0.0.2   localhost/' /etc/hosts
sudo cp -f ~/hosts.new /etc/hosts
