#!/usr/bin/env bash
# this script changes the localhost ip and facebook ip
cp /etc/hosts ~/hosts.new
hos="8.8.8.8	facebook.com"
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "$hos" >> ~/hosts.new

sudo cp -f ~/hosts.new /etc/hosts
